.TH  1 Binclock
.SH NAME
binclock \- an ncurses clock that displays in binary
.SH SYNOPSIS
.B binclock
.RB [ args ]
.SH DESCRIPTION
binclock is a really simple, really light ncurses clock with a bunch
of themes to choose from
.SH OPTIONS
.TP
.B \-h
prints information regarding how to find help. It points you here.
.TP
.B \-t#
picks a theme from the options below
.TP
.B \-s#
picks a colour set from the options below
.SH THEMES
.TP
.B 0: [ ] [ ] [ ] [*] [*] [ ] [*] [*] 
.TP
.B 1: <0> <0> <0> <1> <1> <0> <1> <1> 
.TP
.B 2: ( ) ( ) ( ) (+) (+) ( ) (+) (+) 
.SH COLOUR SETS
.TP
.B 0: H = Red, M = Green, S = Yellow
.TP
.B 1: H = Blue, M = Magenta, S = Cyan
.TP
.B 2: H = Red, M = WHite, S = Blue
